<a href="https://colab.research.google.com/github/aliaghafur/P146222-_Project2/blob/main/_P146222__Project_2_Hotel_Analysis_SEM1_20242025_20250126.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction**

This dataset contains information about hotel bookings for two hotel groups from July, 2015 until August, 2017.  This dataset contains 3024 observations (rows) and 32 variables. This dataset has been taken from github, known as Hotel Data Analysis and has been written by Shridhar Kamathe. The datasets are from three csv files (Data_2015, Data_2016, Data_2017).

- Github Link: https://github.com/shridharkamathe/Hotel-Data-Analysis/tree/main/Hotel%20Data%20Analysis

By analysing this dataset, we can provide valuable insights to assist
and guide related businessess to improve the business, increase their profitability and optimize their business operations. Average daily rate (ADR) is one of the most important for hotel analysis , which can help the hotel increase their revenue. The higher the ADR means that more revenue per occupied room significantly boosts the hotel's overall profitability.

In this dataset contains two types of hotel: City Hotels and Resort Hotels. In my opinion,  these two types differ significantly in terms of their location, primary focus of business and availables amenities. For example, City Hotels typically located in urban centers, close to shopping areas and easily accessible by public transport. In contrast, Resort Hotels are often situated in scenic locations, such as near to beaches, mountains, or lakes.

### Variables Discriptions:
The followings are variables in dataset:

1. **hotel** : type of hotel
2. **is_canceled** : value indicating if the booking is canceled or not (0==no, 1==yes)
3. **lead_time** : no. of days before actual arrival of the guests
4. **arrival_date_year** : year of arrrival date
5. **arrival_date_month** : month of arrival date
6. **arrival_date_week_number** : week no. of year for arrival date
7. **arrival_date_day_of_month** : day of arrival date
8. **stays_in_weekend_nights** : no. of nights (Saturday and Sunday) guest booked
9. **stays_in_week_nights** : no. of nights (Mondat to Fiday) guest booked
10. **adults**: no. of adults
11. **children** : no of children
12. **babies** : no of babies
13. **meal**: Type of meal booked.  (Undefined/SC - no meal package);
(BB - Bed & Breakfast);
HB-Half board: (breakfast and one other meal- usually dinner);
(FB - Full board (breakfast, lunch and dinner)
14. **country** : country of origin (ISO 3155 - 3:2013)
15. **market_segment** : Online TA, Direct, Groups, Offline TA/TO, Complementary, Corporate, Aviation.
(TA-Travel Agents, TO-Tour Operators)
16. **distribution_channel** : TA/TO, Direct, Corporate, GDS.
17. **is_repeated_guest** : (0==no, 1==yes)
18. **previous_cancellations** : no. of previous bookings that were cancelled
19. **previous_bookings_not_canceled** : no of previous bookings that were not cancelled
20. **reserved_room_type**: Code of room type reserved (8 types)
21. **assigned_room_type** : Code for the type of room assigned to the guests (10 types)
22. **booking_changes** : no of changes made to the booking
23. **deposit_type** : No Deposit, Non Refund, Refundable
24. **agent** : ID of travel agency that made the booking
25. **company** : ID of company
26. **days_in_waiting_list** : no. of days the booking was in the waiting list before it was confirmed to the customer
27. **customer_type** : Transient, Transient-Party, Contrac, Group.
28. **adr** : Average daily rate
29. **required_car_parking_spaces** : no. of parking spaces required by the customer
30. **total_of_special_requests** : no. of special requests made by the customer
31. **reservation_status** : Canceled, Check-Out, No-Show
32. **reservation_starus_date** : date at which the last reservation status was updated.

We will use a few of variables that related to our purpose of analysis.

# **Purpose of Analysis**

Our main focus is explore and analyse the following key areas that can help us uncover significant loopholes and gain valuable insights to drive a profitable hotel business.:


1.   Customer Preferred:
    - To analyse the most popular room types book by guests.
    - To determine the most distribution channel.
    - To identify the most frequent type of meal booked by customers.
    - To determine whether guest prefer to stay during weekdays or weekends.

2.   Average Daily Rate (ADR):
    - To understand  how well the hotel is meeting customer expectations in terms of room type.

3.   Cancellation:
    - Does the room assigned to guests, number of days before actual arrival of guests, market segments and type of deposits give an impact to the booking cancellation?

# **Data Cleaning**

In [1]:
# import the library
import pandas as pd
import numpy as np

In [2]:
# read the Data_2015.csv into data frames
df = pd.read_csv('/content/Data_2015.csv')

In [3]:
# dataset only for Data_2015
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,1,4,2015,October,41,7,0,1,1,...,No Deposit,240.0,NaN,0,Transient,58.00,0,3,Canceled,########
1,City Hotel,0,3,2015,August,35,23,2,0,2,...,No Deposit,14.0,NaN,0,Transient,75.00,0,1,Check-Out,25-08-2015
2,City Hotel,1,414,2015,December,49,5,2,1,2,...,Non Refund,1.0,NaN,0,Transient,62.00,0,0,Canceled,23-07-2015
3,City Hotel,0,20,2015,July,30,22,0,2,1,...,No Deposit,1.0,NaN,0,Transient-Party,0.00,0,0,Check-Out,24-07-2015
4,City Hotel,0,117,2015,August,31,1,2,1,2,...,No Deposit,17.0,NaN,0,Transient-Party,94.50,0,0,Check-Out,4/8/2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Resort Hotel,0,73,2015,September,40,27,2,5,2,...,No Deposit,40.0,NaN,0,Contract,93.43,0,0,Check-Out,########
996,Resort Hotel,0,14,2015,November,48,26,0,3,2,...,No Deposit,240.0,NaN,0,Transient,64.00,1,1,Check-Out,29-11-2015
997,City Hotel,1,50,2015,August,35,25,0,4,2,...,No Deposit,1.0,NaN,0,Transient-Party,62.00,0,0,Canceled,6/8/2015
998,City Hotel,1,87,2015,September,39,25,2,3,2,...,Non Refund,1.0,NaN,0,Transient,170.00,0,0,Canceled,9/9/2015
999,Resort Hotel,0,27,2015,November,46,10,0,5,2,...,No Deposit,240.0,NaN,0,Transient,76.00,1,1,Check-Out,15-11-2015

In [4]:
# combine the dataset from different csv file
df_2015 = pd.read_csv('/content/Data_2015.csv')
df_2016 = pd.read_csv('/content/Data_2016.csv')
df_2017 = pd.read_csv('/content/Data_2017.csv')

# concatenate the data frames
merged_df = pd.concat([df_2015, df_2016, df_2017], ignore_index=True)

# print the merged data
print(merged_df)

             hotel  is_canceled  lead_time  arrival_date_year  \
0     Resort Hotel            1          4               2015
1       City Hotel            0          3               2015
2       City Hotel            1        414               2015
3       City Hotel            0         20               2015
4       City Hotel            0        117               2015
...            ...          ...        ...                ...
3019    City Hotel            1        164               2017
3020  Resort Hotel            0        121               2017
3021  Resort Hotel            0          6               2017
3022    City Hotel            1         99               2017
3023  Resort Hotel            1        167               2017

     arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
0               October                        41                          7
1                August                        35                         23
2              December                        49                          5
3                  July                        30                         22
4                August                        31                          1
...                 ...                       ...                        ...
3019              April                        18                         30
3020             August                        31                          5
3021              April                        15                         14
3022              April                        17                         23
3023               June                        24                         11

      stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                           0                     1       1  ...
1                           2                     0       2  ...
2                           2                     1       2  ...
3                           0                     2       1  ...
4                           2                     1       2  ...
...                       ...                   ...     ...  ...
3019                        2                     2       2  ...
3020                        2                     3       2  ...
3021                        0                     2       2  ...
3022                        2                     2       2  ...
3023                        2                     3       1  ...

      deposit_type  agent company days_in_waiting_list    customer_type  \
0       No Deposit  240.0     NaN                    0        Transient
1       No Deposit   14.0     NaN                    0        Transient
2       Non Refund    1.0     NaN                    0        Transient
3       No Deposit    1.0     NaN                    0  Transient-Party
4       No Deposit   17.0     NaN                    0  Transient-Party
...            ...    ...     ...                  ...              ...
3019    No Deposit    9.0     NaN                    0        Transient
3020    No Deposit  240.0     NaN                    0  Transient-Party
3021    No Deposit  240.0     NaN                    0        Transient
3022    No Deposit    9.0     NaN                    0        Transient
3023    No Deposit  240.0     NaN                    0        Transient

        adr  required_car_parking_spaces  total_of_special_requests  \
0      58.0                            0                          3
1      75.0                            0                          1
2      62.0                            0                          0
3       0.0                            0                          0
4      94.5                            0                          0
...     ...                          ...                        ...
3019   99.0                            0                          1
3020  239.0                            0                          1
3021  130.0                            0                          1
3022  108.0                            0                          0
3023  101.0                            0                          2

      reservation_status reservation_status_date
0               Canceled                ########
1              Check-Out              25-08-2015
2               Canceled              23-07-2015
3              Check-Out              24-07-2015
4              Check-Out                4/8/2015
...                  ...                     ...
3019            Canceled              20-03-2017
3020           Check-Out                ########
3021           Check-Out              16-04-2017
3022            Canceled              14-01-2017
3023            Canceled                7/2/2017

[3024 rows x 32 columns]

In [5]:
# to get summary (data type and null values) from dataset using info
merged_df.info()

# covert data type from object to category:
categorical = ['hotel', 'meal', 'country', 'market_segment',
               'distribution_channel', 'reserved_room_type',
               'assigned_room_type', 'deposit_type',
               'customer_type', 'reservation_status']
for col in categorical:
  merged_df[col] = merged_df[col].astype('category')

print('\n-------------------------------------------------------------------\n')
# to verify:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3024 entries, 0 to 3023
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           3024 non-null   object
 1   is_canceled                     3024 non-null   int64
 2   lead_time                       3024 non-null   int64
 3   arrival_date_year               3024 non-null   int64
 4   arrival_date_month              3024 non-null   object
 5   arrival_date_week_number        3024 non-null   int64
 6   arrival_date_day_of_month       3024 non-null   int64
 7   stays_in_weekend_nights         3024 non-null   int64
 8   stays_in_week_nights            3024 non-null   int64
 9   adults                          3024 non-null   int64
 10  children                        3024 non-null   int64
 11  babies                          3024 non-null   int64
 12  meal                            3024 non-null   object
 13  country                         3015 non-null   object
 14  market_segment                  3024 non-null   object
 15  distribution_channel            3024 non-null   object
 16  is_repeated_guest               3024 non-null   int64
 17  previous_cancellations          3024 non-null   int64
 18  previous_bookings_not_canceled  3024 non-null   int64
 19  reserved_room_type              3024 non-null   object
 20  assigned_room_type              3024 non-null   object
 21  booking_changes                 3024 non-null   int64
 22  deposit_type                    3024 non-null   object
 23  agent                           2638 non-null   float64
 24  company                         162 non-null    float64
 25  days_in_waiting_list            3024 non-null   int64
 26  customer_type                   3024 non-null   object
 27  adr                             3024 non-null   float64
 28  required_car_parking_spaces     3024 non-null   int64
 29  total_of_special_requests       3024 non-null   int64
 30  reservation_status              3024 non-null   object
 31  reservation_status_date         3024 non-null   object
dtypes: float64(3), int64(17), object(12)
memory usage: 756.1+ KB

-------------------------------------------------------------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3024 entries, 0 to 3023
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           3024 non-null   category
 1   is_canceled                     3024 non-null   int64
 2   lead_time                       3024 non-null   int64
 3   arrival_date_year               3024 non-null   int64
 4   arrival_date_month              3024 non-null   object
 5   arrival_date_week_number        3024 non-null   int64
 6   arrival_date_day_of_month       3024 non-null   int64
 7   stays_in_weekend_nights         3024 non-null   int64
 8   stays_in_week_nights            3024 non-null   int64
 9   adults                          3024 non-null   int64
 10  children                        3024 non-null   int64
 11  babies                          3024 non-null   int64
 12  meal                            3024 non-null   category
 13  country                         3015 non-null   category
 14  market_segment                  3024 non-null   category
 15  distribution_channel            3024 non-null   category
 16  is_repeated_guest               3024 non-null   int64
 17  previous_cancellations          3024 non-null   int64
 18  previous_bookings_not_canceled  3024 non-null   int64
 19  reserved_room_type              3024 non-null   category
 20  assigned_room_type              3024 non-null   category
 21  booking_changes                 3024 non-null   int64
 22  deposit_type                    3024 non-null   category
 23  agent                           2638 non-null   float64
 24  company                         162 non-null    float64
 25  days_in_waiting_list            3024 non-null   int64
 26  customer_type                   3024 non-null   category
 27  adr                             3024 non-null   float64
 28  required_car_parking_spaces     3024 non-null   int64
 29  total_of_special_requests       3024 non-null   int64
 30  reservation_status              3024 non-null   category
 31  reservation_status_date         3024 non-null   object
dtypes: category(10), float64(3), int64(17), object(2)
memory usage: 554.1+ KB

- The merged dataset 2015 to 2017 expected to have 3024 rows. However df.info() reveals that there are missing values in the 'country', 'agent' and 'company' columns which counts of 3015, 2638 and 162 respectively.

- The merged_df.info() also display the types of data for each columns in merged data frame. Based on the inspection, most data types are match the expectation. The 'hotel' variable, intended to be a categorical variable with the values like 'City Hotel' and 'Resort Hotel', is currently represented as an object type. All other columns that represent categorical data are also type object. Object data type are general-purpose data type for strings, but we can change the type of data to category to make the analysis more efficient and clear.

<font color='red'>**Remember to add comments with hashtags (#) for the code above.**

<font color='red'>**1. What's the purpose of running the above code**

<font color='red'>**2. Based on the output above, do the data types meet your expectations? Please provide an explanation to help guide the readers.**

In [6]:
# create new column 'total_requests'
# sum of 'required_car_parking_spaces' and 'total_of_special_requests'
merged_df['total_requests'] = merged_df['required_car_parking_spaces'] + merged_df['total_of_special_requests']

# create new column 'total_guests'
# sum of 'adults', 'children' and 'babies'
merged_df['total_guests'] = merged_df['adults'] + merged_df['children'] + merged_df['babies']
print(merged_df)

             hotel  is_canceled  lead_time  arrival_date_year  \
0     Resort Hotel            1          4               2015
1       City Hotel            0          3               2015
2       City Hotel            1        414               2015
3       City Hotel            0         20               2015
4       City Hotel            0        117               2015
...            ...          ...        ...                ...
3019    City Hotel            1        164               2017
3020  Resort Hotel            0        121               2017
3021  Resort Hotel            0          6               2017
3022    City Hotel            1         99               2017
3023  Resort Hotel            1        167               2017

     arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
0               October                        41                          7
1                August                        35                         23
2              December                        49                          5
3                  July                        30                         22
4                August                        31                          1
...                 ...                       ...                        ...
3019              April                        18                         30
3020             August                        31                          5
3021              April                        15                         14
3022              April                        17                         23
3023               June                        24                         11

      stays_in_weekend_nights  stays_in_week_nights  adults  ...  company  \
0                           0                     1       1  ...      NaN
1                           2                     0       2  ...      NaN
2                           2                     1       2  ...      NaN
3                           0                     2       1  ...      NaN
4                           2                     1       2  ...      NaN
...                       ...                   ...     ...  ...      ...
3019                        2                     2       2  ...      NaN
3020                        2                     3       2  ...      NaN
3021                        0                     2       2  ...      NaN
3022                        2                     2       2  ...      NaN
3023                        2                     3       1  ...      NaN

      days_in_waiting_list    customer_type    adr  \
0                        0        Transient   58.0
1                        0        Transient   75.0
2                        0        Transient   62.0
3                        0  Transient-Party    0.0
4                        0  Transient-Party   94.5
...                    ...              ...    ...
3019                     0        Transient   99.0
3020                     0  Transient-Party  239.0
3021                     0        Transient  130.0
3022                     0        Transient  108.0
3023                     0        Transient  101.0

     required_car_parking_spaces total_of_special_requests  \
0                              0                         3
1                              0                         1
2                              0                         0
3                              0                         0
4                              0                         0
...                          ...                       ...
3019                           0                         1
3020                           0                         1
3021                           0                         1
3022                           0                         0
3023                           0                         2

      reservation_status  reservation_status_date  total_requests total_guests
0               Canceled                 ########               3            1
1              Check-Out               25-08-2015               1            2
2               Canceled               23-07-2015               0            2
3              Check-Out               24-07-2015               0            1
4              Check-Out                 4/8/2015               0            2
...                  ...                      ...             ...          ...
3019            Canceled               20-03-2017               1            2
3020           Check-Out                 ########               1            2
3021           Check-Out               16-04-2017               1            2
3022            Canceled               14-01-2017               0            2
3023            Canceled                 7/2/2017               2            1

[3024 rows x 34 columns]

In [7]:
# drop column that not related to the analysis
# columns to drop
to_drop = ['arrival_date_week_number', 'arrival_date_day_of_month',
           'adults', 'children', 'babies', 'is_repeated_guest',
           'previous_cancellations', 'previous_bookings_not_canceled',
           'agent', 'company', 'days_in_waiting_list',
           'required_car_parking_spaces','total_of_special_requests',
           'reservation_status_date']

# axis = 1 - specifies that dropping the columns, not rows
# inplace = True - the new df doesnt consist the drop columns
merged_df.drop(to_drop, axis = 1, inplace = True)

#  to display the modified data frame
merged_df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,booking_changes,deposit_type,customer_type,adr,reservation_status,total_requests,total_guests
0,Resort Hotel,1,4,2015,October,0,1,BB,PRT,Online TA,TA/TO,A,A,0,No Deposit,Transient,58.0,Canceled,3,1
1,City Hotel,0,3,2015,August,2,0,BB,ESP,Direct,Direct,A,A,0,No Deposit,Transient,75.0,Check-Out,1,2
2,City Hotel,1,414,2015,December,2,1,BB,PRT,Groups,TA/TO,A,A,0,Non Refund,Transient,62.0,Canceled,0,2
3,City Hotel,0,20,2015,July,0,2,BB,PRT,Groups,TA/TO,A,A,0,No Deposit,Transient-Party,0.0,Check-Out,0,1
4,City Hotel,0,117,2015,August,2,1,HB,ITA,Offline TA/TO,TA/TO,A,A,0,No Deposit,Transient-Party,94.5,Check-Out,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3019,City Hotel,1,164,2017,April,2,2,SC,GBR,Online TA,TA/TO,A,A,0,No Deposit,Transient,99.0,Canceled,1,2
3020,Resort Hotel,0,121,2017,August,2,3,BB,GEO,Online TA,TA/TO,D,D,0,No Deposit,Transient-Party,239.0,Check-Out,1,2
3021,Resort Hotel,0,6,2017,April,0,2,BB,ESP,Online TA,TA/TO,A,A,0,No Deposit,Transient,130.0,Check-Out,1,2
3022,City Hotel,1,99,2017,April,2,2,SC,GBR,Online TA,TA/TO,A,A,0,No Deposit,Transient,108.0,Canceled,0,2
3023,Resort Hotel,1,167,2017,June,2,3,BB,RUS,Online TA,TA/TO,A,A,0,No Deposit,Transient,101.0,Canceled,2,1

- The purpose of this code is to remove the columns that are consider irrelevent for this analysis.This reduces dataset to  focus on the important variables, improve the efficiency and make the dataset smaller and more manageable.

- Here, the columns 'required_car_parking_spaces' and 'total_of_special_requests' are removed because a new column, 'total_requests' contains all the necessary information. The 'total_requests' is created by summing the values from  'required_car_parking_spaces' and 'total_of_special_requests'.

- Similarly, 'adults', 'children' and 'babies' column are dropped after creating the 'total_guest' column that represent the sum of these three columns.

- The remaining variables in the to_drop list are removed because the variables are not directly related to the goals of this analysis. This means that these variables do not contribute to addressing the key questions that this analysis seeks to answer.

<font color='red'>**Comments:**

<font color='red'>**1. Remember to add comments with hashtags (#) for the code above.**

<font color='red'>**- What's the purpose running the above code**

In [8]:
# get unique value
unique_values = merged_df.nunique()
print(unique_values)

hotel                        2
is_canceled                  2
lead_time                  387
arrival_date_year            3
arrival_date_month          12
stays_in_weekend_nights      9
stays_in_week_nights        17
meal                         5
country                     78
market_segment               7
distribution_channel         4
reserved_room_type           8
assigned_room_type          10
booking_changes              9
deposit_type                 3
customer_type                4
adr                        988
reservation_status           3
total_requests               6
total_guests                 6
dtype: int64

<font color='red'>**Comments:**

<font color='red'>**- What's the purpose running the above code. Give some explanation for the benefits of readers**

In [9]:
# column name and its unique values
for column in merged_df.columns:
  unique_values = merged_df[column].unique()
  print(column + ":" + str(unique_values))

hotel:['Resort Hotel', 'City Hotel']
Categories (2, object): ['City Hotel', 'Resort Hotel']
is_canceled:[1 0]
lead_time:[  4   3 414  20 117  34  45 276  51 253  22  40 104 295  80   1  17  42
 323 343 241  90  63  36  37  93 162   0  21  25 178  74   5  29  39  54
 182  79  12  43 101  82 221   9  76 179 257 135 207   6 290   7  10  32
  16  28 309 151 344  69  26  35 214  81 335  98 258  83  55  13  44 277
 219  11 292 140  14 120  38 114 112 297 262  24  46  92  97  30 327 185
 202   2 193 267  87  31  19 287 205 282 224 260 100  23 273 364  72  18
  65 138 122 154 336 289 342  48 358  33 148 102 283 105  27  52 265   8
 326 337  57  61 222 247 294 329 152 332 311 314  53 281  95 227 113  99
  91  58  15 127  50  84 367 244 111  75 274  41  77 304 161  60  67 159
 106 272 123 133  59 286 155  66 254 301 149 132 172 532 129  47 110 164
 136 165 233  89 210 275 231  56  64 147  68 341 141 142  86 168 349 264
 211 334  49 235 124 199 270 340 119  94 259 278 339  71 174 268  70 204
  88 131 107 300 333  85 186 321 234 181 299 245 302 145 195 158 183 256
 130 225 134  78 279 374  73 356 200 216 171 351  62 330 196 137 192 223
  96 293 198 180 108 220 239 363 217 461 383 213 157 346 116 128 139 160
 291 226 125 517 384 382 443 184 103 208 420 143 316 189 298 489 212 386
 169 246 173 310 285 176 115 175 215 188 146 121 177 194 284 126 255 322
 328 228 201 377 249 271 524 240 170 153 426 406 393 187 109 144 166 320
 230 418 243 303 209 280 447 118 475 305 150 251 237 412 269 468 440 242
 197 352 236 396 476 318 407 261 307 448 250 338 405 350 203 423 317 518
 252 313 167 409 395 191 263 156 462 573 206 229 451 347 504 434 566 325
 411 629 163 360 288 545 552 315 238]
arrival_date_year:[2015 2016 2017]
arrival_date_month:['October' 'August' 'December' 'July' 'September' 'November' 'May' 'March'
 'June' 'February' 'April' 'January']
stays_in_weekend_nights:[0 2 3 1 4 9 5 8 6]
stays_in_week_nights:[ 1  0  2  7  3  5  4  8  6 10  9 20 11 14 18 12 19]
meal:['BB', 'HB', 'FB', 'SC', 'Undefined']
Categories (5, object): ['BB', 'FB', 'HB', 'SC', 'Undefined']
country:['PRT', 'ESP', 'ITA', 'GBR', 'IRL', ..., 'AZE', 'AND', 'ZWE', 'TWN', 'GEO']
Length: 79
Categories (78, object): ['AGO', 'ALB', 'AND', 'ARE', ..., 'USA', 'VEN', 'ZAF', 'ZWE']
market_segment:['Online TA', 'Direct', 'Groups', 'Offline TA/TO', 'Complementary', 'Corporate', 'Aviation']
Categories (7, object): ['Aviation', 'Complementary', 'Corporate', 'Direct', 'Groups',
                         'Offline TA/TO', 'Online TA']
distribution_channel:['TA/TO', 'Direct', 'Corporate', 'GDS']
Categories (4, object): ['Corporate', 'Direct', 'GDS', 'TA/TO']
reserved_room_type:['A', 'C', 'D', 'E', 'G', 'F', 'H', 'B']
Categories (8, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
assigned_room_type:['A', 'D', 'H', 'F', 'G', 'C', 'E', 'B', 'I', 'K']
Categories (10, object): ['A', 'B', 'C', 'D', ..., 'G', 'H', 'I', 'K']
booking_changes:[ 0  1  4  2  3 20  5  7 14]
deposit_type:['No Deposit', 'Non Refund', 'Refundable']
Categories (3, object): ['No Deposit', 'Non Refund', 'Refundable']
customer_type:['Transient', 'Transient-Party', 'Contract', 'Group']
Categories (4, object): ['Contract', 'Group', 'Transient', 'Transient-Party']
adr:[ 58.    75.    62.     0.    94.5   39.95  70.    47.    58.95  88.67
 172.    90.    81.34 105.    95.   101.53  55.    86.    60.   170.
  74.   117.22 116.    67.    91.   146.95 115.    61.65  87.    97.
 103.18  98.    88.    36.    71.1  153.    89.2   65.    77.56  50.
 101.5   64.    81.    79.   252.    73.   188.46  12.   133.    83.
  76.5  124.8   85.5   34.    62.8   40.5   78.3  126.   143.5   67.31
  25.    76.67 212.   109.    74.61  88.38 105.3  181.5   88.4  224.67
 179.    26.1   79.39  61.2  120.71 161.   154.8   40.    76.   166.
  32.    55.68  42.3   96.67  69.    95.95 100.    46.5  118.    82.35
  96.3  241.    94.   105.08  89.   146.8   55.6   68.    57.    95.04
  73.51  85.67 124.   186.25 140.   174.25  35.    17.6   43.41 110.
 131.   160.    64.88 245.33 117.2  134.75  49.   133.2   55.44  45.
 104.    86.25  84.   135.    85.   117.    42.    52.8   49.95  19.
  48.42 108.    60.35 120.    87.78  36.13 147.6   77.4  194.    77.96
 107.   128.5   58.3  120.08  73.64  37.29  79.5  196.    58.2    8.
 157.37 154.   123.   164.    36.05 250.   109.4  199.29 110.3  127.5
  96.   148.1  128.    72.76  52.4   45.6   82.    70.84  59.2   68.45
 129.   116.71  99.45 103.84  37.    89.25 111.6  166.6   47.46  48.
  29.06 130.17 103.05  46.   111.65  29.75  22.5  131.14 195.   176.67
  71.69  62.5  205.   156.45 101.    74.25  87.75  13.   105.2   79.74
 111.25 120.6  107.5  192.    55.43 168.67 137.75  39.   127.    62.67
  79.83 179.1  146.    56.98  68.5   72.75  92.45 244.    67.95  95.33
 152.   177.47  99.    78.    43.2  173.   165.   106.8   72.25  39.6
  33.3   51.92  40.05 114.    90.95 118.2  133.21  92.63  57.5  125.
 129.33  96.9  112.2   44.5   77.84  72.5  154.98  77.79 118.17  48.5
  80.   144.43  51.    30.5   47.33  59.85 104.85 231.    55.63 120.43
 155.5  162.   243.   110.7  149.    53.   118.67 112.6  221.    53.1
  89.55  98.67 186.67  26.   117.29 107.43   6.   137.65  44.49 138.6
 165.32  67.4  136.5   63.47 111.   100.8   80.1   71.67  83.5  199.
 113.9  185.   103.28  37.83 103.5  211.    90.64  58.76 105.5   40.96
  52.2   56.   101.65  55.48  54.02 192.6  130.5  102.5  106.    29.
  65.18  78.03 134.    46.4  118.13 147.75  48.74  41.   121.    55.46
  59.13 276.53 144.9   97.5  106.2   43.    38.4  179.6  157.67  45.9
 139.33  66.15 135.2  142.67 110.53 151.25  78.6  136.    29.34 102.33
  74.07  66.29 299.33 150.83 150.53 186.   168.8   39.2  138.   131.2
  89.5   60.5  113.33 121.8  131.1  137.    54.4   68.43 114.71  67.5
  87.5  148.63  69.91 123.5  152.5   52.36  84.47  92.   242.6   25.11
  30.6   92.1  102.41 178.    69.93  90.6   42.5   68.74  93.43 136.67
 125.1   61.4  150.45 159.3  184.   102.   130.    74.8  168.3  110.46
 139.95 209.    83.12 139.   147.    64.64 102.6   79.9  137.7   72.
  69.36  46.18  85.6   79.2  113.46  80.75  46.36  90.9   93.    84.43
 103.7   65.75  93.15  68.47  90.71  62.9  177.77 123.3   76.25 188.01
  98.82 119.   141.   125.2   89.1   69.75  70.11  88.77  74.75 141.3
 118.8   66.02   2.   123.25  59.21  97.75  80.81  77.14 171.6  109.8
 156.   135.15 157.33  51.8   90.67  73.33  81.67  30.    82.8   76.05
 140.4   93.5  145.   168.    69.29  87.71 142.    83.83 181.    58.36
 104.4   82.45 248.89  46.93  66.   156.5  113.4   39.9   93.57 149.4
 109.75  29.8   85.3   63.75  37.8   54.   157.27 103.21 147.3  130.05
 115.94 116.11  91.48 116.1  152.15  86.36 187.   151.    66.7  234.7
  50.4  126.29  63.   121.55 152.4   95.6  177.   102.3  140.13 115.93
 139.88  65.8   91.45  91.63  71.6   49.22 109.83 105.8   43.47 183.5
 109.9  137.14  80.3  103.31 116.95  87.32  57.8   42.29 148.   121.35
  89.91  44.46 119.85  52.27 104.55  57.47 101.33 243.17 146.7   67.99
  86.57 132.6   73.95 207.   160.43 104.67 126.9  134.1  116.33 147.99
  68.64  81.9  129.99  91.67  95.4   75.65  58.45 121.5  146.3  135.9
  91.1  248.    55.8   88.01  90.2   47.4  129.7  210.    93.08  90.1
 144.    38.81 167.45 108.9   44.66 114.3   61.64 139.5  216.9  126.38
 159.9  149.52  92.55  45.37 154.1  103.    93.33 150.3  117.9  101.15
  43.5   92.57  95.86  68.4   98.5  112.   169.   186.3  146.5   68.16
 269.   171.    88.43 183.    96.25 176.33 115.77  79.4   97.2  124.79
  87.3   56.7   55.1  171.2  131.4  128.7   68.42 211.76 120.35 155.
 107.1  232.33  81.77  42.1  132.3  239.43  95.48 126.67  53.85 114.29
 234.    62.75 106.5   43.8   52.02  65.4  154.69  52.56 113.05  50.15
 105.6  107.57 107.95 208.8   75.6  150.8   86.5   68.53 106.65  68.8
 136.44 198.9  150.57 305.    22.    63.9   57.83  75.82  90.68  33.
  77.    95.63  88.8   79.85  68.85 156.25 165.8  120.3  153.3   54.5
  92.9  157.45  76.58  91.9  121.25  66.45  79.43 139.13  98.55  81.5
  60.48 225.   187.5  108.8   77.36  68.55  98.8  108.67 143.33  61.33
 189.   105.04 154.93 109.38 155.25 116.9   63.58  95.02 148.75  64.08
  59.    56.4   49.59 145.8   87.43 157.28  44.07  52.    69.3  185.4
 203.   159.33 208.56  54.9  109.25 143.    76.92  86.75  38.88  74.54
 119.7  137.1  163.   134.37  95.13  69.5   55.89 117.6   73.74  77.77
  88.29 132.   127.8   59.4  284.86  89.31 159.    90.5  114.75  41.87
 144.5  120.86  68.33 203.67 191.57 321.5  291.43 290.67  72.2  150.
  97.33 218.   122.4  112.67 270.   152.1  115.6  151.2  230.   205.18
 132.33  97.36 153.9   39.74 199.5   82.86  86.1  190.   129.2   43.71
 129.97  67.15 131.5  164.6   98.1   94.4   44.    84.69 194.06 231.5
 118.5  192.57  96.91 166.5   39.33 142.38 113.   184.5  201.67 108.59
  40.95  82.08 289.6  264.   119.33 135.7   77.61 119.1  142.2   95.69
  58.31 206.51 134.85 153.07 183.6  100.7  295.5  331.   198.   101.38
 103.2  133.06 247.2  106.75 156.96 172.5   72.83  99.28 284.   117.3
 130.67  65.1   86.91  82.15 115.2  114.4  276.   157.5  151.17  33.6
 177.75 124.67 161.7  131.7   28.5  127.33 193.1  116.5  161.5  180.
 109.95 101.28 174.   105.84 129.67  78.35 215.   128.25  80.76 131.98
  47.72 100.3  150.92  73.39 164.7  119.4  202.5  112.5  138.38 220.
 163.4   83.8   89.76  73.37 206.57  39.8  168.89 113.67 245.    95.2
  85.7   70.25 183.2  199.8  274.    63.01  93.6   52.55  88.2  104.72
 168.5  151.7  153.6   58.6   95.5  126.8   84.73 133.67 195.67  45.5
 313.67  48.9  115.4  134.5  200.   185.75 160.2  174.6  128.74 156.06
  93.38  84.17 134.3   84.15 106.28  87.2  175.    76.32  83.16 141.88
  50.85 137.25 127.24 125.4  172.8  139.67 247.   166.92 130.36 169.2
 148.5  248.1  110.5   82.42 109.1   68.95  86.4  151.14 167.18 108.2
 159.14 228.84 197.1   71.28 219.86 378.    78.31 143.1   94.36  74.6
  79.69  98.94 127.58  91.08 354.   191.    70.2   70.95  66.53 112.12
  82.75  27.5  118.75 226.   112.7  193.   203.75 149.6  158.5  147.13
  41.94 343.   119.57 232.    78.4   60.06  88.39 102.35  51.27  98.6
  42.38 203.11  43.53 337.    86.7   76.03 140.7  129.6  260.    72.42
 105.34 203.33 133.74 133.48  70.4   49.7  108.1   65.83 201.6   60.98
 266.2   82.99 153.33 153.57 108.33  96.4   93.54 239.  ]
reservation_status:['Canceled', 'Check-Out', 'No-Show']
Categories (3, object): ['Canceled', 'Check-Out', 'No-Show']
total_requests:[3 1 0 2 4 5]
total_guests:[1 2 3 4 0 5]

<font color='red'>**Comments:**

<font color='red'>**- What's the purpose running the above code. Give some explanation for the benefits of readers**

In [10]:
# 'meal'- ['BB' 'HB' 'FB' 'SC' 'Undefined']
# Undefined and SC represent the same meaning
# combine 'Undefined' and 'SC'
merged_df['meal'] = merged_df['meal'].replace({'Undefined': 'SC'})
print(merged_df['meal'].unique())

['BB', 'HB', 'FB', 'SC']
Categories (4, object): ['BB', 'FB', 'HB', 'SC']

<ipython-input-10-3275c847ecc5>:4: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  merged_df['meal'] = merged_df['meal'].replace({'Undefined': 'SC'})

In [11]:
# checking for missing value
missing_values = merged_df.isnull().sum()
print(missing_values)

hotel                      0
is_canceled                0
lead_time                  0
arrival_date_year          0
arrival_date_month         0
stays_in_weekend_nights    0
stays_in_week_nights       0
meal                       0
country                    9
market_segment             0
distribution_channel       0
reserved_room_type         0
assigned_room_type         0
booking_changes            0
deposit_type               0
customer_type              0
adr                        0
reservation_status         0
total_requests             0
total_guests               0
dtype: int64

<font color='red'>**Comments:**

<font color='red'>**- What's the purpose running the above code. Give some explanation for the benefits of readers**

<font color='red'>**- Is there any more missing values?**

In [12]:
# filling the missing data
merged_df['country'] = merged_df['country'].fillna('Unknown')

missing_values = merged_df.isnull().sum()
print(missing_values)

TypeError: Cannot setitem on a Categorical with a new category (Unknown), set the categories first

<font color='red'>**Comments:**

<font color='red'>**1. If the code in the previous cell block already shows no missing data, why would you still want to fill in the missing data in current cell block?**

<font color='red'>**2. What is your justification for doing so?**

# **Analysis and Discussion**

In [ ]:
# import the library
import matplotlib.pyplot as plt
import seaborn as sns

### Purpose of Analysis:
1.   Customer Preferred:
    - To analyse the most popular room types book by guests.
    - To determine the most distribution channel.
    - To identify the most frequent type of meal booked by customers.
    - To determine whether guest prefer to stay during weekdays or weekends.

In [ ]:
fig, (ax1, ax2) = plt.subplots(2, 1,  figsize=(15, 15))

# plot country - half of country from dataset
country_counts = merged_df['country'].value_counts().head(40)
colors = sns.color_palette('bright', 40)

# 1st subplot - bar plot
bars_1=ax1.bar(country_counts.index, country_counts, color=colors)
ax1.set_xlabel('Country')
ax1.set_ylabel('Count')
ax1.set_title('Origin of Guest')
ax1.bar_label(bars_1)
ax1.set_xticklabels(country_counts.index, rotation=45, ha='right');


# 2nd subplot - pie chart
# calculate the percentage of 'hotel'
hotel_counts = merged_df['hotel'].value_counts()
hotel_percent = hotel_counts / hotel_counts.sum() * 100

ax2.pie(hotel_percent, labels=hotel_percent.index, autopct='%1.1f%%', startangle=90)
ax2.set_title('Hotel Type')

plt.tight_layout()
plt.show()


- From the bar plot below 'Origin Of Country' shows that Portugal(PTG) is the dominant origin with the highest number of guest, contributing significantly to the overall guest count. The dominance of PTG followed by Great Britain(GBR), France(FRA), Spain(ESP), DEU(Germany), Italy(ITA) and IRL(Ireland)  as the top 10 most highest number of guest indicate that the hotels represented in data may have strong presence or marketing focus in European market. The frequent representation of European countries maybe that the hotels are located in Europe, making them easily accesssible for travelers from others countries.

- The pie chart 'Hotel Type', City Hotel are the most frequent choose by the guests, for approximately 65.6% and Resort Hotels represent the remaining 34.1% which means maybe greater number of customers are choosing to stay in city-accomodation, indicating that City Hotel may be more common based on this dataset.

In [ ]:
# Group data by year and hotel type
hotel_by_year = merged_df.groupby(['arrival_date_year', 'hotel'])['hotel'].count().unstack()

# stacked bar chart
hotel_by_year.plot(kind='bar', stacked=True)

plt.xlabel('Year')
plt.ylabel('Hotel Count')
plt.title('Hotel Type by Year')
plt.legend(title='Hotel Type')
plt.show()

- The stacked bar chart titled 'Hotel Type by Year' provides insights into the distribution of City and Resort hotels over the year from 2015 to 2017. From all three years, the customers preferred City Hotel compared to Resort Hotel. This maybe major cities typically has become the main attraction to the tourist such as museums, entertainment option, and near to transportation hubs, making the City Hotel become the main choice for travelers.

<font color='red'>**Comments:**

<font color='red'>**1. The bar plot shows a trend where City Hotel accommodation increases from 2015 to 2017, while the proportion of Resort Hotel accommodations decreases in the opposite direction.**

<font color='red'>**2. Would you like to comment on this trend?**

<font color='red'>**3. Did you come across any published reports that mention similar observations?**

In [ ]:
# change to CategoricalDtype - specific order (Jan, Feb, ..., Dec)
month_order= ['January', 'February', 'March', 'April', 'May', 'June',
         'July', 'August', 'September', 'October', 'November', 'December']
month_dtype = pd.CategoricalDtype(categories=month_order, ordered=True)
merged_df['arrival_date_month'] = merged_df['arrival_date_month'].astype(month_dtype)

# create new column 'booking_count' - how many booking for evey month
bookings_df = merged_df.groupby(['arrival_date_month', 'hotel'], observed=True)['hotel'].count().reset_index(name='bookings_count')

# line plot for the City Hotel
plt.figure(figsize=(12, 6))
sns.lineplot(x='arrival_date_month', y='bookings_count',
             data=bookings_df[bookings_df['hotel'] == 'City Hotel'],
             marker='o', label='City Hotel')

# line plot for the Resort Hotel
sns.lineplot(x='arrival_date_month', y='bookings_count',
             data=bookings_df[bookings_df['hotel'] == 'Resort Hotel'],
             marker='s', label='Resort Hotel')

plt.title('Booking Trends by Month, Booking Type, and Hotel')
plt.xlabel('Month')
plt.ylabel('Number of Bookings')
plt.legend(title='Hotel and Booking Type', loc='lower right')
plt.xticks(rotation=45, ha='right')
plt.show()

- The graph illustrate the number of bookings for City Hotels across different months of the year. Both hotels types experience varying levels of demand through the year, with August being a peak season for both. Usually July and August fall within summer months, where this months, school having summer break, so many families and individuals will use this time to go for vacation. Futhermore, favorable summer weather conditions often encorage many outdoor activities, further driving demand for both hotels.

- The lowest number of booking for both hotels are in January, this maybe because the peak holiday season just have passed like Christmas and New Year's and people might be recovering travel expenses or back to daily routines which go to school, and work. Beside that, after the excitment and often hectic nature of the holiday season, many people may simply desire a period of rest and relaxation at home, which this situation leading to decrease in travel demand.

In [ ]:
# change to CategoricalDtype - specific order (Jan, Feb, ..., Dec)
month_dtype = pd.CategoricalDtype(categories=month_order, ordered=True)
merged_df['arrival_date_month'] = merged_df['arrival_date_month'].astype(month_dtype)

# create new column adr - which is  average adr
adr_df = merged_df.groupby(['arrival_date_month', 'hotel'], observed=True)['adr'].mean().reset_index()

# line plot for the City Hotel
plt.figure(figsize=(12, 6))
sns.lineplot(x='arrival_date_month', y='adr',
             data=adr_df[adr_df['hotel'] == 'City Hotel'],
             marker='o', label='City Hotel')

# line plot for the Resort Hotel
sns.lineplot(x='arrival_date_month', y='adr',
             data=adr_df[adr_df['hotel'] == 'Resort Hotel'],
             marker='s', label='Resort Hotel')

plt.title('Average Daily Rate (ADR) by Month, Booking Type, and Hotel')
plt.xlabel('Month')
plt.ylabel('ADR')
plt.legend(title='Hotel and Booking Type', loc='upper left')
plt.xticks(rotation=45, ha='right')
plt.show()

- This graph ilustrate the ADR for both City Hotels and Resort Hotels across different months. City Hotels shows a generally upward trend from January to May, followed by a slighly decline towards the end of the year. In contrast, Resort Hotels shows a significant peak in ADR during August, with a subsequent decline in the following months.

- Although, for City Hotel has highest number of booking during summer month (July and August), but for ADR show that decline during that months. This can be attribute to several factors which during this month there is likely a surge in demand for hotel. This increased competition among hotel that can lead to hotel to offer discounts or promotions to attract guests. Beside that, guests often book hotels in advance, especially during peak season, and the hotel might offer earlier booking discount to incentive reservation which lead to a lower ADR.

<font color='red'>**Comment:**

<font color='red'>**1. What is your interpretation of the clear peak in August for Resort Hotel?**

<font color='red'>**2. What could explain the significant increase in ADR during that period?**

In [ ]:
# count the value for 'reserved_room_type'
reserve_room_counts = merged_df['reserved_room_type'].value_counts()

# color
colors = sns.color_palette('bright', 10)

# bar plot
bars_1 = plt.bar(reserve_room_counts.index, reserve_room_counts,color=colors )
plt.xlabel('Room')
plt.ylabel('Count')
plt.title('Reserved Room by Customers')
plt.bar_label(bars_1)
plt.show()

- From the bar chart 'Reserved Room by Customer' above, Room A become the main choose of room than any other type which 2250 reservations. Room D become the second highest with 476 reservation by guests, and the lowest chosen room is Room H. Room A <font color='red'>**might be**</font> the standard room which is the most basic and affordable room type which is maybe make it attractive choice for budget-conscious traveler, including solo or family travelers. In contrast, Room H is executive suite, which is a luxurious suite with larger living area, a separate dining room and kitchenette This suite is typically preferred by affluent guests seeking a high level of comfort and exclusivity.

<font color='red'>**Comments:**

<font color='red'>**1. Could you clarify the exact room types labeled from A to H?**

<font color='red'>**2. The term "might be" could raise concerns with stakeholders, as it suggests uncertainty. This could imply that the exact information wasn’t thoroughly researched, don’t you think?**

<font color='red'>**3. If the information is truly unavailable, you should clearly state the issue regarding the lack of available data.**

In [ ]:
# reserved_room_type
plt.figure(figsize=(12, 6))
sns.countplot(x='reserved_room_type', hue='hotel', data=merged_df)
plt.title('Reserved Room Type by Hotel')
plt.xlabel('Reserved Room Type')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Hotel Type')
plt.show()

- The bar chart 'Reserved RoomType by Hotel'shows that guests at City Hotel reserve Room Types A, B, D, E, F while for guests at Resort Hotel resrve Room Types A, C, D, E, F, G, H.
When we compared both hotels, it obviously shows that for both type of hotels, customers preferred Room A, and Room D also the second choice but for the Room E, Resort Hotel become the higher choice of reservation. This is maybe because Room E is a family room that designed to accommodate families that typically have multiple beds, connecting rooms, or others amenities that would be attractive to resort guests.

<font color='red'>**Comments:**

<font color='red'>**1. Why did you suddenly change the color scheme for City and Resort Hotels? In the previous cell blocks, blue was used for City Hotel and orange for Resort Hotel.**

<font color='red'>**2. Please use a consistent color scheme to avoid confusion and ensure clarity.**

<font color='red'>**3. Please update the color scheme for the whole colab notebook acordingly**

In [ ]:
# distribution_channel
sns.countplot(x='distribution_channel', hue='hotel', data=merged_df)
plt.title('Distribution Channel by Hotel Type')
plt.xlabel('Distribution Channel')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Hotel Type')
plt.show()

- Both hotel groups commonly used Travel Agents (TA) and Tour Operators (TO) as the distribution channels. However, the use of Global Distribution System (GDS) differs, which only used by City Hotel. GDS is the vast computer network that allowed customers to search and book travel products such as hotels, flight and other from various suppliers in single system.

- The high use of TA and TO as distribution channels could be due to some factors like packaged that offered by them, the expertise of travel agents in recommending best hotels that fulfill customers need and their ability to facilitate and assist group booking. The direct booking channel is the second distribution channel that help the guest booking their stays maybe because of spontaneous travel decisions and the desire for greater flexibility and control over the booking process.

In [ ]:
# frequent meal booked by guest
plt.figure(figsize=(12, 6))
sns.countplot(x='meal', hue='hotel', data=merged_df)
plt.title(' Meal by Hotel')
plt.xlabel('Meal Type')
plt.ylabel('Count')
plt.legend(title='Hotel')
plt.show()

- For both hotels, customers preferred to book and have bed and breakfast(BB) type, indicating that  they want to have only breakfast included with their room bookings, while Half Board (HB) is the second most popular meal type option which guest also want to have one other meal.

- This suggests that, customers generally prefer to have at least one meal, typically breakfast, included with their room booking. The small demand for Full Board (FB), encompassing breakfast, lunch and dinner, indicates that guests may prioritize experiencing local cuisine and exploring dining options beyond the hotel, such as trying street food. Additionally, some customers choose no meal package(SC), possibly indicating a preference for budget-conscious travel.

In [ ]:
# plot for'stays_in_weekend_nights' and 'stays_in_week_nights' by 'hotel'
# group data by hotel type
# calculate average for night stay
hotel_stays = merged_df.groupby('hotel')[['stays_in_weekend_nights', 'stays_in_week_nights']].mean().reset_index()

# from 'hotel_stay', there are three column - 'hotel', 'stays_in_weekend_nights', 'stays_in_week_nights'
# add another column (average_night)
# 'stays_in_weekend_nights', 'stays_in_week_nights' become one column = 'stay_type'
hotel_melt = hotel_stays.melt(id_vars=['hotel'], var_name='stay_type', value_name='average_nights')

# create the grouped bar chart
plt.figure(figsize=(10, 6))
sns.barplot(x='hotel', y='average_nights', hue='stay_type', data=hotel_melt, palette='muted')
plt.title('Average Stays in Weekend and Week Nights by Hotel Type')
plt.xlabel('Hotel Type')
plt.ylabel('Average Number of Nights')
plt.legend(title='Stay Type')
plt.show()

 - Although many customers prefers to choose City Hotel, but in terms of time stay at the hotel, guests tend to spend longer durations at Resort Hotels. This is likely due to the fact that business travelers who often have shorter stays for meetings or conferences are more likely to stay at City Hotel. In the other hand, for Resort Hotels attract more leisure travelers who are looking for longer vacations and extended stays. Usually Resort Hotels often located near to beach and outside urban area, so there are many activities that guests can do such as beach volleyball, swimming, sunbathing, spas treatments and others. These will encourage guests to extend their stays and enjoy their leisure time.

- Furthermore, guests also tend to stay more on weekdays while the shorter average stay for weekend maybe because many guests use weekend for short gateways or just to take a time to relax their mind before start a busy workweeks. Another factor that may contribute to this result is the price per room difference between weekdays and weekends. Weekday rates are often lower compared to weekend rates, which can be significantly higher, potentially double from normal price.

### Purpose of Analysis:
2.   ADR:
    - To understand how well the hotel is meeting customer expectations in terms of room type.

In [ ]:
# box plot
# to look at customer preference - the room the guest reserve
sns.boxplot(x='reserved_room_type', y='adr', data=merged_df,
            hue='reserved_room_type' , palette='bright',
           order=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])
plt.title(' Reserved Room Type vs ADR')
plt.xlabel('Reserved Room Type')
plt.ylabel('ADR')
plt.show()

- The box plot shows that every the ADR varies for types of room have. Room type A and B have lower ADR. For Room A, we can see that the range of ADR is narrow and the ADR median is the lowest, we did not compared to Room B. Although Room A is the most popular room reserved by guests, but the ADR is low. This may be because the hotels might used the Room A as a 'loss leader' to attract guests. Once the guests arrived at hotel,the hotel can upsell them on more expensive services or amenities such as offering guests the chance to upgrade to a larger room, discount on spas packages,and others.

Reference: https://www.siteminder.com/r/hotel-upselling/#:~:text=Hotel%20upselling%20is%20the%20practice,stay%2C%20beyond%20their%20initial%20booking.

- Room H have higher median ADR and wider ranges, indicating that these are likely more upscale or premium room types with varying levels of luxury and amenities.

- There are several outliers present in the box plot, particularly for some of the higher-priced room types. These outliers could represent exceptionally high-priced rooms or special offers.

### Purpose of Analysis:
3.   Cancellation:
    - Does the room assigned to guests, number of days before actual arrival of guests, market segments and type of deposits give an impact to the booking cancellation?

In [ ]:
# 'assigned_room_type' vs '_is_canceled'
plt.figure(figsize=(12, 6))
sns.countplot(x='assigned_room_type', hue='is_canceled', data=merged_df, palette='Set2')
plt.title('Assigned Room Type vs. Cancellation')
plt.xlabel('Assigned Room Type')
plt.ylabel('Count')
plt.legend(title='Cancellation', labels= ['No', 'Yes'])
plt.show()

- As we look before, the most popular room choose by guests during resrvation is Room A, but as the plot bar 'Assigned Room Type vs. Cancellation' above show that Room A also has a lower cancellation.

- There maybe some factors that contribute to this observations. Firstly, Room A, with attractive features such as larger size, better view , and potentially affordable in price, may lead to higher guest satisfaction and contribute less likely to cancel. In addition, other than Room A, we can see that the number of non-cancelled booking is generally lower compared to the number of cancellation. This shows that guests satisfied with the assigned room. If the assigned room does not meet their expectation or if unexpected additional cost arise, guests may be more likely to cancel the reservations.

In [ ]:
# lead_time' vs 'is_canceled'
plt.figure(figsize=(10, 6))
sns.histplot(data=merged_df, x='lead_time', hue='is_canceled',
             palette='Set2', multiple='stack')
plt.title('Distribution of Lead Time by Cancellation Status')
plt.xlabel('Lead Time (days)')
plt.ylabel('Count')
plt.legend(title='Cancellation', labels= ['Yes', 'No'])
plt.show()
#

- The bar plot indicates that as the the numbers of days before actual date decrease, the number for guest cancellations generally decrease. However, there is still a chance that the guests will cancel the booking even when they are close to the actual date. This could be due to unforeseen circumstances, last minute changes in plans or other factors.

- The higher frequency of shorter lead times can be influence by few factors. Usually, guests tend to book the room closer to their arrrival date. Other than that, maybe because of spontaneous travel decisions made by customers. Customers may book last-minute trips due to sudden travel plan.

In [ ]:
# count the value for 'market_segment'
ms_counts = merged_df['market_segment'].value_counts()

# color
colors = sns.color_palette('bright', 10)

# bar plot
bars_2 = plt.bar(ms_counts.index, ms_counts,
        color=colors, width=0.5)
plt.xlabel('Market Segment')
plt.ylabel('Count')
plt.title('Type of Market Segment')
plt.xticks(rotation=45, ha='right')
plt.bar_label(bars_2)
plt.show()

- In the context of hotel industry, 'market segment' refers to a group of customers withs similar characteristics.

- The largest segment is Online TA (Travel Agencies), indicating that bookings are made through online travel agencies like Booking.com, Opodo and Expedia and the smallest  segment is aviation which represent the bookings was made by airline crew members.
Additionally, there is a segment call Offline TA/TO which represent booking made through traditional travel agency or tour operator. For group segment, represent booking made by groups, such as families or friends. Other than that, there also have direct, corporate and complementary segment, which direct includes booking was made directly with hotel, which through call or hotel's website. Corporate refers to booking made by companies for their employees or business travel and lastly complementary segment might make booking through partnerships with other busuiness such as airlines or tour operators.

- Reference: https://www.canarytechnologies.com/post/hotel-market-segmentation#5-common-hotel-market-segments-worth-getting-to-know

In [ ]:
# 'market_segment' vs 'is_cancel' - diff type 'hotel'
# create the catplot
cp = sns.catplot(x='market_segment', hue='is_canceled', col='hotel',
            data=merged_df, kind='count', palette='Set2',
            height=5, aspect=1.5, legend=False)

# set titles and labels
cp.fig.suptitle('Market Segment vs Cancellation Status')
cp.set_xlabels('Market Segment')
cp.set_ylabels('Count')
cp.add_legend(title='Cancellation', labels= ['No', 'Yes'])
cp.set_xticklabels(rotation=45, ha='right')

plt.show()

- The chart show the relationship between market segment and cancellation status, whether the reservation was canceled or not for both types of hotels. Both hotels shows that 'Online TA' has highest number for both canceled and non canceled reservations. According to 'Group' segment, in City Hotel, number of cancellation is fewer, while in Resort Hotel, number of cancellation is higher. For both hotel types, 'Complementary' and 'Aviation' have very low number of cancellations as well as the number of booking.

- Online TA such as Booking.com have a wide reach and are easily accessible to people who want to travel. This high visibility leads to significant volume of bookings through this channel and also will giving travelers to easy of booking hotel and also easy in canceling. This is one of the reason that might lead to a higher number pf cancellations compared to traditional booking methods.

In [ ]:
# 'deposit_type' vs 'is_cancel' - diff type 'hotel'
# create the catplot
cp = sns.catplot(x='deposit_type', hue='is_canceled', col='hotel',
            data=merged_df, kind='count', palette='Set2',
            height=5, aspect=1.5, legend=False)

# set titles and labels
cp.fig.suptitle('Type of Deposit vs Cancellation Status')
cp.set_xlabels('Type of Deposit')
cp.set_ylabels('Count')
cp.add_legend(title='Cancellation', labels= ['No', 'Yes'])
cp.set_xticklabels(rotation=45, ha='right')

plt.show()

- From the dataset, there are three types of deposits which are no deposit, no  refund, and refundable. For both hotels have the same pattern where the reservation with no deposit have the highest number of cancellation.

- A 'no deposit' policy allows guests to book reservations without paying any money upfront. Guests might easily reserve multiples room without they need to worry about any financial penalty, since there is no financial commitment. This will increase the probability of overbooking for the hotel and lead to higher potential of cancellation. Besides that, guests who choose the no deposit options might be easily switch to another hotel if they find a better deal or encounter unexpected expenses.  

- However, the non refundable option has higher number of non-canceled reservation. This type requires to pay a deposit up ahead that is no money will be paid back to guests if they cancel the reservation within a certain time frame. The lower number of cancellation may be because of guests tend to carefully think before decide decision regarding their travel plan. Financial penalty is one of the main reasons that guests need to take consideration about their travel plan. Guests who have already paid for the room resrvation will lose their money if cancellation is made.

# **Conclusion**


- In conclusion, by analysing customer preference, Average Daily Rate (ADR) and relationship of various factors with cancellation, both hotels can gain some valuable insights to optimize operation, increase profitability and also help creat a positive business impact.

- Analysing the reserved room types by guests can reveal the most frequently booked room type. Both hotels should prioritize the availability and potentially adjust pricing strategies for high demand rooms. Next, analysing distribution channels, type of meal, and weekend or weekdays stay can help business understanding customers preference that can guide business to strucure successful marketing campaigns and provide services that align with guests preferences. In addition, with the understanding values of ADR with different assigned room types can help business management  make informed decisions about pricing strategies and room inventory management to maximize revenue.

- Lastly, understanding the factors such as room assigned to guests, number of days before actual arrival of guests, market segments and type of deposits taht maybe contribute to cancellations can help implement strategies to reduce cancellations and improve guest satisfaction, such as offer flexible cancellation options to accommodate guest needs and reduce the risk of last-minute cancellations, mplement deposit policies that balance guest flexibility with revenue protection and others.

- By continuously monitoring these key areas and adapting strategies based on the insights gained, hotels can enhance the guest experience, optimize revenue, and achieve sustainable growth. Other than that, further analysis is required to help the business maintain and improve their revenue in the futures.